#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# SMF Startup script for the firewaller agent.
#

set -o xtrace

. /lib/svc/share/smf_include.sh

TOP=$(unset CDPATH; cd $(dirname $0)/../; pwd)


# Add firewaller log rotation
/usr/sbin/logadm -w firewaller_logs -C 168 -S 1g -c -p 1h \
    -t '/var/log/sdc/upload/firewaller_\$nodename_%FT%H:%M:%S.log' \
    '/var/svc/log/*firewaller*.log'

# Make sure firewaller logs get rotated before the SMF log rotation takes over
/usr/sbin/logadm -r smf_logs
/usr/sbin/logadm -w smf_logs -C 8 -c -s 1m '/var/svc/log/*.log'


/usr/bin/ctrun -l child -o noorphan ${TOP}/node/bin/node \
    --abort_on_uncaught_exception \
    ${TOP}/main.js &

exit $SMF_EXIT_OK
