#!/usr/node/bin/node --abort_on_uncaught_exception

/*
 * Copyright (c) 2013, Joyent, Inc. All rights reserved.
 *
 * Firewaller agent
 */

var assert = require('assert-plus');
var bunyan = require('/usr/node/node_modules/bunyan');
var config = require('../lib/config');
var fs = require('fs');
var firewaller = require('../lib/agent');
var path = require('path');
var VError = require('verror').VError;



// --- Main entry point



var CONFIG;
var LOG = bunyan.createLogger({
    name: 'firewaller',
    level: 'debug'
});

try {
    CONFIG = JSON.parse(fs.readFileSync(
        path.normalize(__dirname + '/../config.json'), 'utf-8'));
    assert.object(CONFIG.fwapi, 'CONFIG.fwapi');
    // Let the FwAgent constructor handle the rest of the validation
} catch (parseErr) {
    LOG.error(parseErr, 'Error parsing config file');
    process.exit(1);
}


config.sdc(function (err, sdcConfig) {
    if (err) {
        LOG.error(err, 'Error getting SDC config');
        return;
    }

    ['fwapi_domain', 'vmapi_domain'].forEach(function (key) {
        if (!sdcConfig.hasOwnProperty(key)) {
            throw new VError(
                'Could not find property "%s" in config file', key);
        }
    });

    config.getSysinfoValue('UUID', function (err2, uuid) {
        if (err2) {
            LOG.error(err2, 'Error getting sysinfo');
            return;
        }

        CONFIG.log = LOG;
        CONFIG.serverUUID = uuid;
        CONFIG.fwapi.host = sdcConfig.fwapi_domain;
        CONFIG.vmapi = { host: sdcConfig.vmapi_domain };

        var agent;
        try {
            agent = firewaller.create(CONFIG);
        } catch (createErr) {
            LOG.error(createErr, 'Error creating agent');
            return;
        }

        agent.sync(function (err3) {
            if (err3) {
                LOG.error(err3, 'Error doing initial sync');
                return;
            }

            agent.connect(function (err4) {
                if (err4) {
                    LOG.error(err4, 'Error connecting to %s',
                        sdcConfig.fwapi_domain);
                    return;
                }

                LOG.info('Connected to %s', sdcConfig.fwapi_domain);
            });
        });
    });
});
